services:
  vpn_handler:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    volumes:
      - ../../../vpn_handler/etc/specs/vpn_hander_openapi.yaml:/tmp/api.oas3.yml:ro
    ports:
      - '9000:4010'

  server_handler:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    volumes:
      - ../../../server_handler/server_handler_openapi.yaml:/tmp/api.oas3.yml:ro
    ports:
      - '3000:4010'