services:
  mine_server:
    build:
      context: .
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        FORGE_VERSION: ${FORGE_VERSION}
        NETWORK_ID: ${NETWORK_ID}
    env_file:
      - .env
    ports:
      - 25565:25565
      - 9993:9993
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./mods:/srv/minecraft/mods
      - ./world:/srv/minecraft/world
      - ./config/eula.txt:/srv/minecraft/eula.txt
      - ./config/server.properties:/srv/minecraft/server.properties
      - ./config/user_jvm_args.txt:/srv/minecraft/user_jvm_args.txt
    stdin_open: true
    tty: true
    restart: unless-stopped
