/*
 * ZeroTier Central API
 *
 * ZeroTier Central Network Management Portal API.<p>All API requests must have an API token header specified in the <code>Authorization: token xxxxx</code> format.  You can generate your API key by logging into <a href=\"https://my.zerotier.com\">ZeroTier Central</a> and creating a token on the Account page.</p><p>eg. <code>curl -X GET -H \"Authorization: token xxxxx\" https://api.zerotier.com/api/v1/network</code></p><p><h3>Rate Limiting</h3></p><p>The ZeroTier Central API implements rate limiting.  Paid users are limited to 100 requests per second.  Free users are limited to 20 requests per second.</p> <p> You can get the OpenAPI spec here as well: <code>https://docs.zerotier.com/api/central/ref-v1.json</code></p>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberConfig {
    /// Allow the member to be a bridge on the network
    #[serde(rename = "activeBridge", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub active_bridge: Option<Option<bool>>,
    /// Is the member authorized on the network
    #[serde(rename = "authorized", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authorized: Option<Option<bool>>,
    #[serde(rename = "capabilities", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Option<Vec<i32>>>,
    /// Time the member was created or first tried to join the network
    #[serde(rename = "creationTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<Option<i64>>,
    /// ID of the member node.  This is the 10 digit identifier that identifies a ZeroTier node.
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    /// Public Key of the member's Identity
    #[serde(rename = "identity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Option<String>>,
    /// List of assigned IP addresses
    #[serde(rename = "ipAssignments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_assignments: Option<Option<Vec<String>>>,
    /// Time the member was authorized on the network
    #[serde(rename = "lastAuthorizedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_authorized_time: Option<Option<i64>>,
    /// Time the member was deauthorized on the network
    #[serde(rename = "lastDeauthorizedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_deauthorized_time: Option<Option<i64>>,
    /// Exempt this member from the IP auto assignment pool on a Network
    #[serde(rename = "noAutoAssignIps", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub no_auto_assign_ips: Option<Option<bool>>,
    /// Member record revision count
    #[serde(rename = "revision", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revision: Option<Option<i32>>,
    /// Allow the member to be authorized without OIDC/SSO
    #[serde(rename = "ssoExempt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sso_exempt: Option<Option<bool>>,
    /// Array of 2 member tuples of tag [ID, tag value]
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<Vec<models::MemberConfigTagsInnerInner>>>>,
    /// Major version of the client
    #[serde(rename = "vMajor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub v_major: Option<Option<i32>>,
    /// Minor version of the client
    #[serde(rename = "vMinor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub v_minor: Option<Option<i32>>,
    /// Revision number of the client
    #[serde(rename = "vRev", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub v_rev: Option<Option<i32>>,
    /// Protocol version of the client
    #[serde(rename = "vProto", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub v_proto: Option<Option<i32>>,
}

impl MemberConfig {
    pub fn new() -> MemberConfig {
        MemberConfig {
            active_bridge: None,
            authorized: None,
            capabilities: None,
            creation_time: None,
            id: None,
            identity: None,
            ip_assignments: None,
            last_authorized_time: None,
            last_deauthorized_time: None,
            no_auto_assign_ips: None,
            revision: None,
            sso_exempt: None,
            tags: None,
            v_major: None,
            v_minor: None,
            v_rev: None,
            v_proto: None,
        }
    }
}

