name: Bot CI

on:
  push:
    paths:
      - "bot/**"
  pull_request:
    paths:
      - "bot/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Verificar linting (flake8)
      #   run: |
      #     pip install flake8
      #     flake8 .

      - name: Executar testes
        run: |
          pip install pytest
          pytest
