name: Redis Configuration CI

on:
  pull_request:
    paths:
      - "redis_pubsub/docker-compose.yaml"
      - "redis_pubsub/redis.conf"
  workflow_dispatch:

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Redis with configuration
        run: docker compose up -d
        working-directory: redis_pubsub

      - name: Wait for Redis to start
        run: sleep 1

      - name: Check Redis status
        run: docker compose exec -T redis redis-cli PING
        working-directory: redis_pubsub

      - name: Remove container
        run: docker compose down
        working-directory: redis_pubsub