name: Redis Configuration CI

on:
  push:
    paths:
      - "redis-pub-sub/docker-compose.yaml"
      - "redis-pub-sub/redis.conf"
  pull_request:
    paths:
      - "redis-pub-sub/docker-compose.yaml"
      - "redis-pub-sub/redis.conf"

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Redis with configuration
        run: docker compose up -d
        working-directory: redis-pub-sub
          
      - name: Check Redis status
        run: docker exec redis-test redis-cli PING

      - name: Remove container
        run: docker compose down
        working-directory: redis-pub-sub
